# Generated by Django 2.2.7 on 2019-12-13 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchWord1', models.TextField()),
                ('searchWord2', models.TextField()),
                ('searchWord3', models.TextField()),
                ('WordAndOR1', models.TextField()),
                ('WordAndOR2', models.TextField()),
                ('Country', models.TextField()),
                ('Status', models.TextField()),
                ('searchInventor1', models.TextField()),
                ('searchInventor2', models.TextField()),
                ('searchInventor3', models.TextField()),
                ('InvAndOR1', models.TextField()),
                ('InvAndOR2', models.TextField()),
                ('URLfinal', models.TextField()),
                ('requestDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
